agent:
  name: "{{ .agent.targetName }}"
  deploymentTarget:
    enabled: true
    {{- if .agent.scriptPods.image }}
    image: "{{ .agent.scriptPods.image }}"
    {{- end }}
    initial:
      environments: [{{ quoteEach .agent.targetEnvironments  }}]
      tags: [{{ quoteEach .agent.targetRoles }} ]
      {{- if .agent.targetTenantedDeploymentParticipation }}
      targetTenantedDeploymentParticipation: {{ .agent.targetTenantedDeploymentParticipation }}
      {{ end}}
      {{- if .agent.targetTenants }}
      tenants: [{{ quoteEach .agent.targetTenants }}]
      {{- end }}
      {{- if .agent.targetTenantTags }}
      tenantTags: [{{ quoteEach .agent.targetTenantTags }}]
      {{- end }}
      {{- if .agent.defaultNamespace }}
      defaultNamespace: "{{ .agent.defaultNamespace}}"
      {{- end }}
  targetName: null
  targetEnvironments: null
  {{- if .agent.defaultNamespace }}
  defaultNamespace: null
  {{- end}}
  targetRoles: null
  {{- if .agent.targetTenantTags }}
  targetTenantTags: null
  {{- end}}
  {{- if .agent.targetTenants }}
  targetTenants: null
  {{- end}}
  {{- if .agent.targetTenantedDeploymentParticipation }}
  targetTenantedDeploymentParticipation: null
  {{- end}}
  {{- if .agent.scriptPods.image }}
  scriptPods:
    image: null
  {{- end}}
