agent:
  name: "{{ .agent.targetName }}"
  deploymentTarget:
    enabled: true
    {{- if .agent.scriptPods.image }}
    image: "{{ .agent.scriptPods.image }}"
    {{- end }}
    initial:
      environments: [{{ quoteEach .agent.targetEnvironments  }}]
      tags: [{{ quoteEach .agent.targetRoles }} ]
      {{- if .agent.targetTenantedDeploymentParticipation }}
      targetTenantedDeploymentParticipation: {{ .agent.targetTenantedDeploymentParticipation }}
      {{ end}}
      {{- if .agent.targetTenants }}
      tenants: [{{ quoteEach .agent.targetTenants }}]
      {{- end }}
      {{- if .agent.targetTenantTags }}
      tenantTags: [{{ quoteEach .agent.targetTenantTags }}]
      {{- end }}
      {{- if .agent.defaultNamespace }}
      defaultNamespace: "{{ .agent.defaultNamespace}}"
      {{- end }}


